"""Export service — compile book chapters into .docx, .pdf, and .txt files."""

from __future__ import annotations

import io
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF

from app.services import db_service


# ── Markdown heading helper ───────────────────────────────────────────────────

_HEADING_RE = re.compile(r"^(#{1,3})\s+(.+)$")


def _strip_md_heading(text: str) -> tuple[int, str] | None:
    """Return (level, title) if text is a Markdown heading, else None."""
    m = _HEADING_RE.match(text)
    if m:
        return len(m.group(1)), m.group(2).strip()
    return None


# ── DOCX Export ───────────────────────────────────────────────────────────────


def export_docx(book: dict, chapters: list[dict]) -> bytes:
    """Generate a Word document from book data and return bytes."""
    doc = Document()

    # Title page
    title_para = doc.add_heading(book["title"], level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph("")  # spacer

    # Table of contents placeholder
    doc.add_heading("Table of Contents", level=1)
    for ch in chapters:
        doc.add_paragraph(
            f"Chapter {ch['chapter_number']}: {ch.get('title', 'Untitled')}",
            style="List Number",
        )
    doc.add_page_break()

    # Chapters
    for ch in chapters:
        doc.add_heading(
            f"Chapter {ch['chapter_number']}: {ch.get('title', 'Untitled')}",
            level=1,
        )
        content = ch.get("content") or ""
        for paragraph_text in content.split("\n\n"):
            stripped = paragraph_text.strip()
            if not stripped:
                continue
            heading = _strip_md_heading(stripped)
            if heading:
                level, title = heading
                doc.add_heading(title, level=min(level, 3))
            else:
                doc.add_paragraph(stripped)
        doc.add_page_break()

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── PDF Export ────────────────────────────────────────────────────────────────


class _BookPDF(FPDF):
    """Custom PDF with header/footer for the book."""

    def __init__(self, book_title: str):
        super().__init__()
        self.book_title = book_title

    def header(self):
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 10, self.book_title, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def export_pdf(book: dict, chapters: list[dict]) -> bytes:
    """Generate a PDF from book data and return bytes."""
    pdf = _BookPDF(book["title"])
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.ln(60)
    pdf.cell(0, 20, book["title"], align="C")
    pdf.ln(40)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, "Generated by Book Generator", align="C")

    # Chapters
    for ch in chapters:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 18)
        chapter_heading = (
            f"Chapter {ch['chapter_number']}: {ch.get('title', 'Untitled')}"
        )
        pdf.cell(0, 15, chapter_heading)
        pdf.ln(20)

        content = ch.get("content") or ""
        pdf.set_font("Helvetica", "", 11)

        for line in content.split("\n"):
            stripped = line.strip()
            if not stripped:
                pdf.ln(5)
                continue

            heading = _strip_md_heading(stripped)
            if heading:
                level, title = heading
                sizes = {1: 17, 2: 15, 3: 13}
                pdf.set_font("Helvetica", "B", sizes.get(level, 13))
                pdf.ln(5)
                pdf.cell(0, 10, title)
                pdf.ln(12)
                pdf.set_font("Helvetica", "", 11)
            else:
                # Encode to latin-1 for Helvetica; replace unsupported chars
                safe_text = stripped.encode("latin-1", errors="replace").decode("latin-1")
                pdf.multi_cell(0, 6, safe_text)
                pdf.ln(2)

    return bytes(pdf.output())


# ── TXT Export ────────────────────────────────────────────────────────────────


def export_txt(book: dict, chapters: list[dict]) -> str:
    """Generate plain-text output."""
    lines: list[str] = []
    lines.append("=" * 60)
    lines.append(book["title"].upper())
    lines.append("=" * 60)
    lines.append("")

    for ch in chapters:
        lines.append("-" * 60)
        lines.append(
            f"CHAPTER {ch['chapter_number']}: "
            f"{ch.get('title', 'Untitled').upper()}"
        )
        lines.append("-" * 60)
        lines.append("")
        lines.append(ch.get("content") or "")
        lines.append("")

    return "\n".join(lines)


# ── Upload to Supabase Storage ────────────────────────────────────────────────


def upload_to_storage(
    book_id: str,
    file_bytes: bytes,
    fmt: str,
) -> str:
    """Upload the compiled file to Supabase Storage and return the URL."""
    content_type_map = {
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "pdf": "application/pdf",
        "txt": "text/plain",
    }
    path = f"books/{book_id}/final_draft.{fmt}"
    url = db_service.upload_file(
        bucket="book-exports",
        path=path,
        file_bytes=file_bytes,
        content_type=content_type_map.get(fmt, "application/octet-stream"),
    )
    return url
