"""Outline API routes — generate, approve, regenerate outlines."""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException

from app.models.enums import OutlineStatus
from app.models.schemas import BookResponse, MessageResponse, OutlineApproval
from app.pipelines import outline_pipeline
from app.services import db_service

router = APIRouter(prefix="/api/books/{book_id}/outline", tags=["Outlines"])


@router.post("/generate", response_model=BookResponse)
def generate_outline(book_id: UUID):
    """Trigger outline generation for a book.

    Requires notes_on_outline_before to exist on the book record.
    If notes_on_outline_after exists, it will be incorporated
    into a regenerated outline.
    """
    try:
        updated = outline_pipeline.generate_outline(str(book_id))
        return updated
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    except Exception as exc:
        raise HTTPException(500, f"Outline generation failed: {exc}")


@router.post("/approve", response_model=BookResponse)
def approve_outline(book_id: UUID, body: OutlineApproval):
    """Approve the outline or request changes with additional notes.

    If status = 'notes_requested' and notes_on_outline_after is provided,
    the outline can be regenerated by calling /generate again.
    """
    try:
        updated = outline_pipeline.approve_outline(
            book_id=str(book_id),
            status=body.status_outline,
            notes_after=body.notes_on_outline_after,
        )

        # If the editor requested notes and provided them, auto-regenerate
        if (
            body.status_outline == OutlineStatus.NOTES_REQUESTED
            and body.notes_on_outline_after
        ):
            updated = outline_pipeline.generate_outline(str(book_id))

        return updated
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    except Exception as exc:
        raise HTTPException(500, f"Outline approval/regeneration failed: {exc}")
